MQTT usr/passwd and Delta parameter for PLC
ocervinka/plccoms-mqtt-bridge pull request #8
Opened 2021-01-04 18:48 UTC by AcMetelka

2021-01-24 23:02 UTC, ocervinka requested changes
Diky za ta vylepseni. Obe jsou uzitecna. Ohledne te delty bych to udelal trochu jinak, viz poznamka v kodu. Muzu ti s tim pomoct, nebo to udelat a pak na to mrknes.

2021-11-21 23:36 UTC, AcMetelka commented on src/main/java/ocervinka/plcmqttbridge/config/VarMappingConfig.java
> +            @JsonProperty("delta") String stateTopicDelta,
Nechal jsem tu deltu jako string asi proto, že to je stejně ASCII request Telnetem a nikde se s tím jako s číslem nemanipuluje.

2021-11-21 23:37 UTC, AcMetelka commented on src/main/java/ocervinka/plcmqttbridge/config/VarMappingConfig.java
> +    public final MessageFormat stateTopicDelta;
Nechal jsem tu deltu jako string asi proto, že to je stejně ASCII request Telnetem a nikde se s tím jako s číslem nemanipuluje.

2021-11-21 23:48 UTC, AcMetelka commented on src/main/java/ocervinka/plcmqttbridge/config/VarMappingConfig.java
> +            @JsonProperty("delta") String stateTopicDelta,
Jo pravda, upravil jsem na varDelta.

2021-11-22 00:16 UTC, AcMetelka commented on src/main/java/ocervinka/plcmqttbridge/PlcMqttBridge.java
> +        this.plccomsClient = new PlccomsClient(this::onList, this::onDiff, varMappingsByVariable);
Upravil jsem onList metodu, přetypoval výstupní hodnotu a příslušné proměnné tak, aby se pro EN: a pro GET: vytvořily dva listy proměnných. Pro EN obsahují i deltu, pro GET nikoli (s deltou to pak PLCComS odmítne). Lépe jsem to nevymyslel, snad to bude takhle vyhovující. Jsem v Java totál lama. :)

2021-12-04 19:22 UTC, ocervinka commented
@AcMetelka Diky, za ty upravy. Jsou to uzitecny veci, ktery stoji za to pridat. Rozdelme to na dva nezavisly PR at se vzajemne neblokuji. Stejne spolu vubec nesouvisi.

1. Moznost pridat do konfiguracniho souboru polozky `usename` a `password`, ktere budou pouzity pro authentikaci MQTT klienta. Tohle je v podstate hotovy.

2. Moznost definovat v konfiguracnim souboru minimalni zmenu hodnoty a tuto pak poslat do `plccoms`, ktery bude sam filtrovat mensi zmeny a generovat mensi pocet eventu pro `plccoms-mqtt-bridge` Uz je to docela dobry, ale jeste to potrebuje trochu upravit. Pristi tyden se k tomu snad dostanu.

Vsechny ostatni veci pak budou pres dalsi issue/PR. Issue mozna lepsi pouzit, kdyz neni jasny jak neco vyresit. PR, kdyz uz je to jasny.

2021-12-04 20:47 UTC, ocervinka commented
@AcMetelka prosim mrkni na ten prvni [PR](https://github.com/ocervinka/plccoms-mqtt-bridge/pull/11) V podstate jsou to tvoje zmeny plus unit test configurace.

2021-12-12 23:58 UTC, ocervinka commented
If there is no objection this PR can be closed.
* MQTT authentication has been addressed by https://github.com/ocervinka/plccoms-mqtt-bridge/pull/11
* Variable delta has been addressed by https://github.com/ocervinka/plccoms-mqtt-bridge/pull/12

2022-02-06 10:49 UTC, ocervinka commented
Closing this PR. Already addressed by:
* MQTT authentication has been addressed by https://github.com/ocervinka/plccoms-mqtt-bridge/pull/11
* Variable delta has been addressed by https://github.com/ocervinka/plccoms-mqtt-bridge/pull/12

2022-02-06 10:49 UTC, closed without merging